/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetojava2023;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 910640
 */
public class ClienteEditar extends javax.swing.JFrame {

    /**
     * Creates new form ClienteEditar
     */
    public ClienteEditar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cpf = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter tele = new javax.swing.text.MaskFormatter("###.###.###-##");
            cpf = new javax.swing.JFormattedTextField(tele);
        }
        catch (Exception e){
        }
        jLabel6 = new javax.swing.JLabel();
        rua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dataNasc = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter tele = new javax.swing.text.MaskFormatter("##/##/####");
            dataNasc = new javax.swing.JFormattedTextField(tele);
        }
        catch (Exception e){
        }
        jLabel5 = new javax.swing.JLabel();
        buscador = new javax.swing.JButton();
        tel = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter tele = new javax.swing.text.MaskFormatter("(##) # ####-####");
            tel = new javax.swing.JFormattedTextField(tele);
        }
        catch (Exception e){
        }
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(cpf);
        cpf.setBounds(180, 130, 140, 30);

        jLabel6.setText("BAIRRO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 260, 86, 14);
        getContentPane().add(rua);
        rua.setBounds(180, 290, 140, 30);

        jLabel7.setText("RUA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 300, 99, 14);
        getContentPane().add(bairro);
        bairro.setBounds(180, 250, 88, 30);

        jLabel8.setText("NÚMERO");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(130, 340, 72, 14);
        getContentPane().add(num);
        num.setBounds(180, 330, 88, 30);

        jLabel9.setText("CIDADE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 380, 99, 14);

        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });
        getContentPane().add(cidade);
        cidade.setBounds(180, 370, 160, 30);
        getContentPane().add(email);
        email.setBounds(180, 210, 130, 30);

        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 20, 21, 14);

        jLabel2.setText("NOME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 60, 53, 14);

        jLabel3.setText("DATA NASCIMENTO ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 100, 99, 14);

        voltar.setBackground(new java.awt.Color(255, 51, 51));
        voltar.setText("VOLTAR");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(540, 20, 90, 30);

        editar.setBackground(new java.awt.Color(255, 204, 51));
        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(400, 140, 80, 40);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(180, 10, 88, 30);

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome);
        nome.setBounds(180, 50, 140, 30);

        jLabel4.setText("CPF");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 140, 69, 14);
        getContentPane().add(dataNasc);
        dataNasc.setBounds(180, 90, 120, 30);

        jLabel5.setText("EMAIL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 220, 99, 14);

        buscador.setBackground(new java.awt.Color(255, 204, 51));
        buscador.setText("BUSCAR");
        buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorActionPerformed(evt);
            }
        });
        getContentPane().add(buscador);
        buscador.setBounds(400, 90, 80, 40);
        getContentPane().add(tel);
        tel.setBounds(180, 170, 140, 30);

        jLabel11.setText("TELEFONE");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(120, 180, 60, 14);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_far.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 760, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed

        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        try{
           
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetojava2023","root","");
            
            java.sql.Statement st = conn.createStatement();
            int cod = Integer.parseInt(id.getText());
            st.executeUpdate(" UPDATE cliente SET nome ='"+ this.nome.getText() +"' ,dataNasc = '"+ this.dataNasc.getText() + "',"
                + "cpf='"+ this.cpf.getText() + "', tel = '" +this.tel.getText()+"',"
                + "email='"+ this.email.getText() + "',bairro='"
                + this.bairro.getText() + "',rua='"+ this.rua.getText() + "',num='" + this.num.getText() + "',cidade='"+ this.cidade.getText() 
                + "'WHERE id="+cod+"");

            JOptionPane.showMessageDialog(rootPane,"Funcionario editado com sucesso");
            id.setText(null);
            nome.setText(null);
            dataNasc.setText(null);
            cpf.setText(null);
            email.setText(null);
            bairro.setText(null);
            rua.setText(null);
            num.setText(null);
            cidade.setText(null);
        }catch (SQLException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(rootPane, e);
        };
    }//GEN-LAST:event_editarActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetojava2023","root","");
            java.sql.Statement st = conn.createStatement();

            st.executeQuery ("select * from cliente where id = " + id.getText() + "");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                nome.setText(rs.getString("nome"));
                dataNasc.setText(rs.getString("dataNasc"));
                cpf.setText(rs.getString("cpf"));
                tel.setText(rs.getString("cpf"));
                email.setText(rs.getString("email"));
                bairro.setText(rs.getString("bairro"));
                rua.setText(rs.getString("rua"));
                num.setText(rs.getString("num"));
                cidade.setText(rs.getString("cidade"));
            }
        }
        catch (SQLException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_buscadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro;
    private javax.swing.JButton buscador;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField dataNasc;
    private javax.swing.JButton editar;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField num;
    private javax.swing.JTextField rua;
    private javax.swing.JTextField tel;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
