package projetojava2023;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 910640
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Login");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        logar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 400));
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login30.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 110, 30, 60);

        logar1.setBackground(new java.awt.Color(153, 255, 204));
        logar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logar1.setText("LOGIN");
        logar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logar1ActionPerformed(evt);
            }
        });
        getContentPane().add(logar1);
        logar1.setBounds(130, 240, 80, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/senha30.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 180, 40, 40);

        campoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLoginActionPerformed(evt);
            }
        });
        getContentPane().add(campoLogin);
        campoLogin.setBounds(100, 130, 140, 30);

        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(campoSenha);
        campoSenha.setBounds(100, 180, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2306532nova.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel1.setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -330, 600, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoginActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetojava2023", "root", "");
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("select * from login");
           
            ResultSet rs = st.getResultSet();
            
            boolean encontrou = false;
            
            while (rs.next()) {
               encontrou = true;
               if((campoLogin.getText().equals(rs.getString("usuario"))) || (campoLogin.getText().equals(rs.getString("email"))) && campoSenha.getText().equals(rs.getString("senha"))){
                   encontrou = true;
                   if(campoSenha.getText().equals(rs.getString("senha"))){
                     TelaPrincipal home = new TelaPrincipal();
                     home.setVisible(true);
                     this.dispose();
                     home.mostraLogado(campoLogin.getText());
                   }
               } if(!encontrou) {
                    JOptionPane.showMessageDialog(rootPane, "Usuário ou senha incorreto");
                    campoLogin.setText(null);
                    campoSenha.setText(null);
               }  
            }
        }catch(SQLException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }


    }//GEN-LAST:event_campoSenhaActionPerformed

    private void logar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logar1ActionPerformed
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetojava2023", "root", "");
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("select * from login");
           
            ResultSet rs = st.getResultSet();
            
            boolean encontrou = false;
            
            while (rs.next()) {
               encontrou = true;
               if((campoLogin.getText().equals(rs.getString("usuario"))) || (campoLogin.getText().equals(rs.getString("email"))) && campoSenha.getText().equals(rs.getString("senha"))){
                   encontrou = true;
                   if(campoSenha.getText().equals(rs.getString("senha"))){
                     TelaPrincipal home = new TelaPrincipal();
                     home.setVisible(true);
                     this.dispose(); 
                   }
               } if(!encontrou) {
                    JOptionPane.showMessageDialog(rootPane, "Usuário ou senha incorreto");
                    campoLogin.setText(null);
                    campoSenha.setText(null);
               }  
            }
        }catch(SQLException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }//GEN-LAST:event_logar1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logar1;
    // End of variables declaration//GEN-END:variables
}
