/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetojava2023;

import java.awt.Container;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 910640
 */
public class NotaFiscalTabela extends javax.swing.JFrame {

 public void tabelaCompleta() {
       final DefaultTableModel modelo = new DefaultTableModel();
       JTable tabela = new JTable(modelo);
       
       
      
        getContentPane().setBackground(UIManager.getColor("Button.focus"));
        setTitle("Gerenciamento de Produto");

             // modelo.addRow(new Object[]{codProduto, lote, validade, descricao, nome, quantidade, preco});
        modelo.addColumn("Id");
        modelo.addColumn("Data");
        modelo.addColumn("Quantidade retirada");
        modelo.addColumn("Preço");
        modelo.addColumn("Código do Produto");
        modelo.addColumn("Funcionário");
        modelo.addColumn("Cliente"); 
        
             
        try {
         
             Class.forName("com.mysql.jdbc.Driver");
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetojava2023", "root", "");
             java.sql.Statement st = conn.createStatement();
             st.executeQuery("select * from notafiscal");
             ResultSet rs = st.getResultSet();
             
                while (rs.next()) {
                String id = rs.getString("id");
                String data = rs.getString("data");
                String qtdRetirada= rs.getString("qtdRetirada");
                String preco = rs.getString("preco");
                String codProduto = rs.getString("codProduto");
                String funcionario = rs.getString("funcionario");
                String cliente = rs.getString("cliente");
                
                modelo.addRow(new Object[]{id, data, qtdRetirada, preco, codProduto, funcionario, cliente});
                }
        } catch (SQLException | ClassNotFoundException e) {
             JOptionPane.showMessageDialog(rootPane, e);
             }//Fim try

        tabela.setPreferredScrollableViewportSize(new Dimension(575, 500));

        Container c = getContentPane();
        getContentPane().setLayout(null);

             // adicionando uma barra de rolagem
        JScrollPane scrollPane = new JScrollPane(tabela);
        scrollPane.setBounds(12, 120, 1165, 603);
        c.add(scrollPane);

             setSize(596, 601); // tamanho da tabela
             setVisible(true); // torna tabela visível
       
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public NotaFiscalTabela() {
       
        tabelaCompleta();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1041, 806));
        setMinimumSize(new java.awt.Dimension(1241, 806));
        getContentPane().setLayout(null);

        voltar.setBackground(new java.awt.Color(255, 51, 51));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(30, 20, 61, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_far.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1260, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        
        
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaFiscalTabela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
