/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetojava2023;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 910640
 */
public class NotaFiscalEditar extends javax.swing.JFrame {

    /**
     * Creates new form NotaFiscalEditar
     */
    public NotaFiscalEditar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cliente = new javax.swing.JTextField();
        funcionario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        data = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter tele = new javax.swing.text.MaskFormatter("##/##/####");
            qtdRetirada = new javax.swing.JFormattedTextField(tele);
        }
        catch (Exception e){
        }
        jLabel4 = new javax.swing.JLabel();
        qtdRetirada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buscador = new javax.swing.JButton();
        codProduto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(preco);
        preco.setBounds(180, 130, 140, 30);

        jLabel6.setText("CLIENTE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 260, 86, 14);
        getContentPane().add(cliente);
        cliente.setBounds(180, 250, 130, 30);
        getContentPane().add(funcionario);
        funcionario.setBounds(180, 210, 130, 30);

        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 20, 21, 14);

        jLabel2.setText("DATA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 60, 53, 14);

        jLabel3.setText("QUANTIDADE RETIRADA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 150, 14);

        voltar.setBackground(new java.awt.Color(255, 51, 51));
        voltar.setText("VOLTAR");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(540, 20, 90, 30);

        editar.setBackground(new java.awt.Color(255, 204, 51));
        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(400, 140, 80, 40);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(180, 10, 88, 30);

        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        getContentPane().add(data);
        data.setBounds(180, 50, 140, 30);

        jLabel4.setText("PREÇO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 140, 69, 14);
        getContentPane().add(qtdRetirada);
        qtdRetirada.setBounds(180, 90, 140, 30);

        jLabel5.setText("FUNCIONÁRIO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 220, 99, 14);

        buscador.setBackground(new java.awt.Color(255, 204, 51));
        buscador.setText("BUSCAR");
        buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorActionPerformed(evt);
            }
        });
        getContentPane().add(buscador);
        buscador.setBounds(400, 90, 80, 40);
        getContentPane().add(codProduto);
        codProduto.setBounds(180, 170, 140, 30);

        jLabel11.setText("COIDGO DO PRODUTO");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 180, 160, 14);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_far.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 760, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed

        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        try{

            Class.forName("com.mysql.jdbc.Driver");

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetojava2023","root","");

            java.sql.Statement st = conn.createStatement();
            int cod = Integer.parseInt(id.getText());
            st.executeUpdate(" UPDATE notafiscal SET data ='"+ this.data.getText() +"' ,qtdRetirada = '"+ this.qtdRetirada.getText() + "',"
                + "preco='"+ this.preco.getText() + "', codProduto = '" +this.codProduto.getText()+"',"
                + "funcionario='"+ this.funcionario.getText() + "',cliente='"
                + this.cliente.getText() + "'WHERE id="+cod+"");

            JOptionPane.showMessageDialog(rootPane,"Nota Fiscal editado com sucesso");
            data.setText(null);
            qtdRetirada.setText(null);
            preco.setText(null);
            codProduto.setText(null);
            funcionario.setText(null);
            cliente.setText(null);
            
        }catch (SQLException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(rootPane, e);
        };
    }//GEN-LAST:event_editarActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed

    private void buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetojava2023","root","");
            java.sql.Statement st = conn.createStatement();

            st.executeQuery ("select * from notafiscal where id = " + id.getText() + "");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                data.setText(rs.getString("data"));
                qtdRetirada.setText(rs.getString("qtdRetirada"));
                preco.setText(rs.getString("preco"));
                codProduto.setText(rs.getString("codProduto"));
                funcionario.setText(rs.getString("funcionario"));
                cliente.setText(rs.getString("cliente"));
                
            }
        }
        catch (SQLException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_buscadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaFiscalEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscador;
    private javax.swing.JTextField cliente;
    private javax.swing.JTextField codProduto;
    private javax.swing.JTextField data;
    private javax.swing.JButton editar;
    private javax.swing.JTextField funcionario;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField preco;
    private javax.swing.JTextField qtdRetirada;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
