/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetojava2023;

import java.awt.AWTException;
import java.awt.Desktop;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author 910640
 */
public class NotaFiscalGerenciamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaNotaFiscal
     */
    public NotaFiscalGerenciamento() {
        initComponents();
        setTitle("GERAR NOTA FISCAL");
        listaCliente();
        listaProduto();
        
    }
    
    public void listaCliente(){
        try {
            
             Class.forName("com.mysql.jdbc.Driver");
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetojava2023", "root", ""); 
             java.sql.Statement st = conn.createStatement();
             st.executeQuery("select * from cliente");
             ResultSet rs = st.getResultSet();
             while(rs.next()){
                 String nome = rs.getString("nome");
                 nomeItem.addItem(nome);
             }
        } catch (SQLException | ClassNotFoundException e) {
             JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    public void listaProduto(){
        try {

                 Class.forName("com.mysql.jdbc.Driver");
                 Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetojava2023", "root", ""); 
                 java.sql.Statement st = conn.createStatement();
                 st.executeQuery("select * from produto");
                 ResultSet rs = st.getResultSet();
                 while(rs.next()){
                     String nome = rs.getString("nome");
                     itemProduto.addItem(nome);
                 }
            } catch (SQLException | ClassNotFoundException e) {
                 JOptionPane.showMessageDialog(rootPane, e);
            }
    }
    public class TakeShoots {
            private BufferedImage image;
            private Robot robot;
            private int padLeft, padTop, w, h;
            public TakeShoots() {
                    // settings for game canvas
                    padLeft = 185;
                    padTop = 209;
                    w = 640;
                    h = 480;

                try {
                        robot = new Robot();                    
                    } catch (AWTException e) {

                    }            

                    System.out.println("Waiting 5 seg...");

            try {        
                Thread.sleep(5000);
          } catch (InterruptedException e){

          }

                System.out.println("Initializing thread...");
                TSThread t = new TSThread(1);
                t.start();

            }
            class TSThread extends Thread {
             int howManyTimes;
                     File file;

             TSThread(int times) {
                 this.howManyTimes = times;
             }


             public void run() {
                 for(int i = 0; i <= this.howManyTimes; i++){
                               image = robot.createScreenCapture(new Rectangle(padLeft, padTop, w, h));
                                    file = new File("image"+i+".png");

                                    try{                                
                                        ImageIO.write(image,"png", file);
                                    }catch(IOException e){

                                    }

                                    file = null;
                                    image = null;              

                                    try {
                        Thread.sleep(1); //Time bettwen each photo
                            } catch (InterruptedException e){

                            }

                 }
             }
         }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        nomeItem = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        itemProduto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        quantiP = new javax.swing.JTextField();
        GerarNotaFiscal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cadastrar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        tabela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(null);

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(30, 90, 101, 23);

        nomeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeItemActionPerformed(evt);
            }
        });
        getContentPane().add(nomeItem);
        nomeItem.setBounds(270, 250, 110, 30);

        jLabel1.setText("TOTAL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 340, 190, 14);

        getContentPane().add(itemProduto);
        itemProduto.setBounds(430, 250, 110, 30);

        jLabel2.setText("NOME DO CLIENTE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 220, 120, 14);

        jLabel4.setText("NOME DO PRODUTO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 220, 130, 14);
        getContentPane().add(quantiP);
        quantiP.setBounds(590, 250, 120, 30);

        GerarNotaFiscal.setText("GERAR NOTA FISCAL");
        GerarNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarNotaFiscalActionPerformed(evt);
            }
        });
        getContentPane().add(GerarNotaFiscal);
        GerarNotaFiscal.setBounds(20, 30, 170, 40);

        jLabel3.setText("QUANTIDADE DO PRODUTO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(590, 220, 190, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 360, 120, 30);

        jLabel5.setText("A NOTA FISCAL ESTÁ DENTRO DE PROJETOJAVA2023");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 30, 420, 30);

        jLabel6.setText("(Coloque o total da compra)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 370, 160, 20);

        cadastrar.setBackground(new java.awt.Color(51, 204, 0));
        cadastrar.setText("CADASTRAR");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(970, 30, 100, 30);

        editar.setBackground(new java.awt.Color(255, 204, 51));
        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(860, 30, 90, 30);

        excluir.setBackground(new java.awt.Color(255, 51, 51));
        excluir.setText("EXCLUIR");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        getContentPane().add(excluir);
        excluir.setBounds(760, 30, 90, 30);

        tabela.setBackground(new java.awt.Color(153, 255, 51));
        tabela.setForeground(new java.awt.Color(0, 51, 51));
        tabela.setText("TABELA");
        tabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelaActionPerformed(evt);
            }
        });
        getContentPane().add(tabela);
        tabela.setBounds(970, 90, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        TelaPrincipal home = new TelaPrincipal();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void nomeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeItemActionPerformed
        
    }//GEN-LAST:event_nomeItemActionPerformed

    private void GerarNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarNotaFiscalActionPerformed
        new TakeShoots();
        Desktop.getDesktop();
        
    }//GEN-LAST:event_GerarNotaFiscalActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        NotaFiscalCadstrar home = new NotaFiscalCadstrar();
        home.setVisible(true);
    }//GEN-LAST:event_cadastrarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        NotaFiscalEditar home = new NotaFiscalEditar();
        home.setVisible(true);
    }//GEN-LAST:event_editarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        NotaFiscalExcluir home = new NotaFiscalExcluir();
        home.setVisible(true);
    }//GEN-LAST:event_excluirActionPerformed

    private void tabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelaActionPerformed
        NotaFiscalTabela home = new NotaFiscalTabela();
        home.setVisible(true);
    }//GEN-LAST:event_tabelaActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaFiscalGerenciamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GerarNotaFiscal;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton editar;
    private javax.swing.JButton excluir;
    private javax.swing.JComboBox<String> itemProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> nomeItem;
    private javax.swing.JTextField quantiP;
    private javax.swing.JButton tabela;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
