/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetojava2023;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.runtime.Debug.id;

/**
 *
 * @author 910640
 */
public class ProdutoEditar extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoEditar
     */
    public ProdutoEditar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        codProduto = new javax.swing.JTextField();
        lote = new javax.swing.JTextField();
        validade = new javax.swing.JTextField();
        descricao = new javax.swing.JTextField();
        preco = new javax.swing.JTextField();
        quantidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        buscador = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 450));
        setUndecorated(true);
        getContentPane().setLayout(null);

        voltar.setBackground(new java.awt.Color(255, 51, 51));
        voltar.setText("VOLTAR");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(620, 10, 80, 30);

        codProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(codProduto);
        codProduto.setBounds(180, 10, 150, 30);

        lote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loteActionPerformed(evt);
            }
        });
        getContentPane().add(lote);
        lote.setBounds(180, 50, 150, 30);
        getContentPane().add(validade);
        validade.setBounds(180, 90, 150, 30);
        getContentPane().add(descricao);
        descricao.setBounds(180, 130, 150, 30);

        preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoActionPerformed(evt);
            }
        });
        getContentPane().add(preco);
        preco.setBounds(180, 250, 150, 30);
        getContentPane().add(quantidade);
        quantidade.setBounds(180, 210, 150, 30);

        jLabel1.setText("CÓDIGO DO PRODUTO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(21, 20, 150, 14);

        jLabel2.setText("LOTE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 60, 53, 14);

        jLabel3.setText("VALIDADE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 100, 80, 14);

        jLabel4.setText("DESCRIÇÃO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 140, 69, 14);

        jLabel5.setText("QUANTIDADE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 220, 99, 14);

        jLabel6.setText("PREÇO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 260, 86, 14);

        jLabel13.setText("NOME");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(140, 180, 60, 14);
        getContentPane().add(nome);
        nome.setBounds(180, 170, 150, 30);

        buscador.setBackground(new java.awt.Color(255, 204, 51));
        buscador.setText("BUSCAR");
        buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorActionPerformed(evt);
            }
        });
        getContentPane().add(buscador);
        buscador.setBounds(520, 100, 80, 40);

        editar.setBackground(new java.awt.Color(255, 204, 51));
        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(520, 150, 80, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_far.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 980, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed

        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void codProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codProdutoActionPerformed

    private void loteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loteActionPerformed

    private void precoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoActionPerformed

    private void buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetojava2023","root","");
            java.sql.Statement st = conn.createStatement();

            st.executeQuery ("select * from produto where codProduto = " + codProduto.getText() + "");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                lote.setText(rs.getString("lote"));
                validade.setText(rs.getString("validade"));
                descricao.setText(rs.getString("descricao"));
                nome.setText(rs.getString("nome"));
                quantidade.setText(rs.getString("quantidade"));
                preco.setText(rs.getString("preco"));
             }
        }
        catch (SQLException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_buscadorActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        try{

            Class.forName("com.mysql.jdbc.Driver");

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetojava2023","root","");

            java.sql.Statement st = conn.createStatement();
            int cod = Integer.parseInt(codProduto.getText());
            st.executeUpdate(" UPDATE produto SET lote ='"+ this.lote.getText() +"' ,validade = '"+ this.validade.getText() + "',"
                + "descricao='"+ this.descricao.getText() + "', nome = '" +this.nome.getText()+"',"
                + "quantidade='"+ this.quantidade.getText() + "',preco='" + this.preco.getText()
                + "'WHERE codProduto="+cod+"");

            JOptionPane.showMessageDialog(rootPane,"Produto editado com sucesso");
            codProduto.setText(null);
            lote.setText(null);
            validade.setText(null);
            descricao.setText(null);
            nome.setText(null);
            preco.setText(null);
            quantidade.setText(null);
        }catch (SQLException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(rootPane, e);
        };
    }//GEN-LAST:event_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscador;
    private javax.swing.JTextField codProduto;
    private javax.swing.JTextField descricao;
    private javax.swing.JButton editar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lote;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField preco;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTextField validade;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
