/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetojava2023;

import java.awt.Container;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 910640
 */
public class ProdutoGerenciamento extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoGerenciamento
     */
    public void tabelaCompleta() {
       final DefaultTableModel modelo = new DefaultTableModel();
       JTable tabela = new JTable(modelo);
       
       
      
        getContentPane().setBackground(UIManager.getColor("Button.focus"));
        setTitle("Gerenciamento de Produto");

             // modelo.addRow(new Object[]{codProduto, lote, validade, descricao, nome, quantidade, preco});
        modelo.addColumn("Código do Produto");
        modelo.addColumn("Lote");
        modelo.addColumn("Validade");
        modelo.addColumn("Descrição");
        modelo.addColumn("Nome");
        modelo.addColumn("Quantidade");
        modelo.addColumn("Preço"); 
        
             
        try {
         
             Class.forName("com.mysql.jdbc.Driver");
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetojava2023", "root", "");
             java.sql.Statement st = conn.createStatement();
             st.executeQuery("select * from produto");
             ResultSet rs = st.getResultSet();
             
                while (rs.next()) {
                String codProduto = rs.getString("codProduto");
                String lote = rs.getString("lote");
                String validade = rs.getString("validade");
                String descricao = rs.getString("descricao");
                String nome = rs.getString("nome");
                String quantidade = rs.getString("quantidade");
                String preco = rs.getString("preco");
                
                modelo.addRow(new Object[]{codProduto, lote, validade, descricao, nome, quantidade, preco});
                }
        } catch (SQLException | ClassNotFoundException e) {
             JOptionPane.showMessageDialog(rootPane, e);
             }//Fim try

        tabela.setPreferredScrollableViewportSize(new Dimension(575, 500));

        Container c = getContentPane();
        getContentPane().setLayout(null);

             // adicionando uma barra de rolagem
        JScrollPane scrollPane = new JScrollPane(tabela);
        scrollPane.setBounds(12, 120, 1165, 603);
        c.add(scrollPane);

             setSize(596, 601); // tamanho da tabela
             setVisible(true); // torna tabela visível
       
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public ProdutoGerenciamento() {
        tabelaCompleta();
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Gerenciamento de Produto");
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        campoBusca = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(null);

        voltar.setBackground(new java.awt.Color(255, 51, 51));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(30, 20, 61, 30);

        excluir.setBackground(new java.awt.Color(255, 51, 51));
        excluir.setText("EXCLUIR");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        getContentPane().add(excluir);
        excluir.setBounds(530, 20, 90, 30);

        editar.setBackground(new java.awt.Color(255, 204, 51));
        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(640, 20, 90, 30);

        cadastrar.setBackground(new java.awt.Color(51, 204, 0));
        cadastrar.setText("CADASTRAR");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(880, 20, 100, 30);

        atualizar.setBackground(new java.awt.Color(51, 255, 51));
        atualizar.setText("ATUALIZAR");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        getContentPane().add(atualizar);
        atualizar.setBounds(760, 20, 100, 30);

        campoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(campoBusca);
        campoBusca.setBounds(1320, 250, 140, 30);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(1340, 210, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_far.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(941, 896));
        jLabel1.setMinimumSize(new java.awt.Dimension(941, 896));
        jLabel1.setPreferredSize(new java.awt.Dimension(941, 796));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -160, 1260, 1220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        TelaPrincipal home = new TelaPrincipal();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        ProdutoExcluir home = new ProdutoExcluir();
        home.setVisible(true);
    }//GEN-LAST:event_excluirActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        ProdutoEditar home = new ProdutoEditar();
        home.setVisible(true);
    }//GEN-LAST:event_editarActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        ProdutoCadastrar home = new ProdutoCadastrar();
        home.setVisible(true);
    }//GEN-LAST:event_cadastrarActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        ProdutoGerenciamento home = new ProdutoGerenciamento();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atualizarActionPerformed

    private void campoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscaActionPerformed

    }//GEN-LAST:event_campoBuscaActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String buscarnome = campoBusca.getText();
        this.dispose();
        FunGerenciamento fun = new FunGerenciamento(buscarnome);
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoGerenciamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JButton editar;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
