package projetojava2023;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 910640
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     * 
     * 
     * 
     * 
     * @param campoLogin
     */
 
    public void mostraLogado(String campoLogin){
       mostraNome.setText(campoLogin);
    }
    public TelaPrincipal() {
     initComponents();
     this.setLocationRelativeTo(null);
     setTitle("Famácia Vida Infinita");
     
     
    }
    
       


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        teste2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mostraNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        funcionario = new javax.swing.JMenu();
        funGerenciamento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        clientesGerenciamento = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        produtoGerenciamento = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        notaFiscal = new javax.swing.JMenuItem();
        adcionar = new javax.swing.JMenu();
        gerenciarLogin = new javax.swing.JMenuItem();

        jTextField1.setText("FUNCIONARIO SELECIADO ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jLabel1.setText("Funcionário logado:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1150, 160, 110, 50);

        mostraNome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mostraNome.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                mostraNomeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(mostraNome);
        mostraNome.setBounds(520, 40, 210, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("Take care of your body, it's the only place you have to live.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 220, 770, 70);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("A segurança do sistema depende de você. Por favor, seja cuidadoso ao trabalhar");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 520, 1060, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setText("Welcome");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 40, 130, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_far.jpg"))); // NOI18N
        jLabel2.setText("MOSTRAR NOTA FISCAL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-120, -50, 1463, 896);

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        funcionario.setText("Funcionários");
        funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioActionPerformed(evt);
            }
        });

        funGerenciamento.setText("Gerenciamento de Usuários");
        funGerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funGerenciamentoActionPerformed(evt);
            }
        });
        funcionario.add(funGerenciamento);

        jMenuBar1.add(funcionario);

        jMenu2.setText("Clientes");

        clientesGerenciamento.setText("Gerenciamento de Clientes");
        clientesGerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesGerenciamentoActionPerformed(evt);
            }
        });
        jMenu2.add(clientesGerenciamento);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Produto");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        produtoGerenciamento.setText("Gerenciamento de Produto");
        produtoGerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoGerenciamentoActionPerformed(evt);
            }
        });
        jMenu7.add(produtoGerenciamento);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Notal Fiscal");

        notaFiscal.setText("Gerar Nota Fiscal");
        notaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaFiscalActionPerformed(evt);
            }
        });
        jMenu8.add(notaFiscal);

        jMenuBar1.add(jMenu8);

        adcionar.setText("Login");
        adcionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adcionarActionPerformed(evt);
            }
        });

        gerenciarLogin.setText("Gerenciar Login");
        gerenciarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarLoginActionPerformed(evt);
            }
        });
        adcionar.add(gerenciarLogin);

        jMenuBar1.add(adcionar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioActionPerformed
        
    }//GEN-LAST:event_funcionarioActionPerformed

    private void funGerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funGerenciamentoActionPerformed
        FunGerenciamento home = new FunGerenciamento("");
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_funGerenciamentoActionPerformed

    private void mostraNomeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_mostraNomeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_mostraNomeAncestorAdded

    private void clientesGerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesGerenciamentoActionPerformed
        ClientesGerenciamento home = new ClientesGerenciamento("");
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clientesGerenciamentoActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void produtoGerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoGerenciamentoActionPerformed
        ProdutoGerenciamento home = new ProdutoGerenciamento();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_produtoGerenciamentoActionPerformed

    private void notaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaFiscalActionPerformed
        NotaFiscalGerenciamento home = new NotaFiscalGerenciamento();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_notaFiscalActionPerformed

    private void adcionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adcionarActionPerformed
        
    }//GEN-LAST:event_adcionarActionPerformed

    private void gerenciarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarLoginActionPerformed
        if (mostraNome.getText().equals("viktor")){
            LonginGerenciar home = new LonginGerenciar();
            home.setVisible(true);
            this.dispose();
        }else{
        JOptionPane.showMessageDialog(rootPane, "Somente Viktor tem permissão para acessar essa área");
        }
    }//GEN-LAST:event_gerenciarLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adcionar;
    private javax.swing.JMenuItem clientesGerenciamento;
    private javax.swing.JMenuItem funGerenciamento;
    private javax.swing.JMenu funcionario;
    private javax.swing.JMenuItem gerenciarLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel mostraNome;
    private javax.swing.JMenuItem notaFiscal;
    private javax.swing.JMenuItem produtoGerenciamento;
    private javax.swing.JLabel teste2;
    // End of variables declaration//GEN-END:variables
}
